<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create</title>
    <script src="js/new_code.js"></script>
    <link rel="stylesheet" href="css/new_code.css">
    <style><#include "css/new_code.css"></style>
    <script><#include "js/new_code.js"></script>
</head>
<body>
<textarea id="code_snippet" class="code_input"></textarea>
<br>
<button id="send_snippet" type="submit" class="submit_button" onclick="send()">Submit</button>
</body>
</html>